### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by marijnvandevoorde** [Iamlowlo/ordering-angular#1]
Hi Carlos,

Just a small thing probably, but there's a depencency issue with the npm packages. I'll just attach the npm log, but it's because html-webpack-plugin is looking for webpack@\* which resolves to the 1.xx branch I guess. 

We already had a look at the code but would love to have a look at the actual app as well. Thanks!

The teamleader dev team :-)

[npm-debug.txt](https://github.com/Iamlowlo/ordering-angular/files/482858/npm-debug.txt)

**Comment by Iamlowlo** [comment]
Hi Marijn,

Sorry to hear that. I finished late yesterday and I forgot to test it on a
greenfield laptop.
I've researched a bit and it seems a problem with an outdated Node/Npm
version.
Here at a Linux I've experienced the same problem and finally solved
upgrading. My versions here are: Node 4.4.7 and Npm 3.10.7
Finally, maybe you found out another problem with gulp (it's an open issue
they have, but I didn't noticed on my own laptop). You may execute `sudo
npm install -g gulp-cli` or if you are in windows OS being on console
window with admin rights.

Sorry again for the trouble. If anything else happens just tell me.

Regards.

2016-09-20 16:41 GMT+02:00 marijn works notifications@github.com:

**Comment by marijnvandevoorde** [comment]
Oh boy, that was exactly it, just updated npm and that worked. Please ignore this issue :-)
